### ISSUE TITLE
Projects can't be edited

### ISSUE THREAD

**Issue by YasRavenheart** [silencesys/Sanatorium#6] opened 2015-05-20 12:22 UTC
Once created, projects can't be edited. Editing a project throws "_Something went wrong. Please Try again later..._"

**Repro**:
1. Go to Posts -> Create project in Admin
2. Create a new project and save it
3. Go to Posts -> View posts
4. Edit your newly created project
5. Try to change something and save the project.
6. Observe the error above

**Tested on**:
Google Chrome  42.0.2311.152 m

**Comment by silencesys** [comment] 2015-05-20 17:43
Fixed in 254b21faccf74986ca6c8cddc8a9ba5c79da7ed8. 
It was caused by wrong route which had variable at 5th place not 4th as it is in main.js. Now is this route replaced by default post edit route and layout changes are made in controller.

**Closed by silencesys** 2015-05-20 17:43 UTC
Labels: bug
